### ISSUE TITLE
Fix Code Coverage in SonarCloud

### ISSUE THREAD

**Issue by wltrf** [DPigeon/Money-Tree#105]
**Describe the bug**
In SonarCloud, the code coverage shows low percentage. This is primarly because it includes test files and config files that are not related to feature implementation.

**To Reproduce**
1. Go on the sonarcloud page for either frontend or backend
2. Look at code coverage metric

**Expected behavior**
Code coverage should be the same as in the generated reports.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Need to exclude .spec files for frontend.
Need to specify coverage report for backend

Bug to be discussed @razine-bensari @Alessandro100

**Comment by Alessandro100** [comment]
If you still need to discuss this, let's setup a meeting on slack. Also we created a 'bug' template to use when reporting bugs. It seems to be missing and I'm currently investigating it. Just a heads up for the future

**Comment by wltrf** [comment]
As discussed, **/*.spec.ts files excluded from sonar coverage
Still need to fix/look into the backend coverage part

**Comment by Alessandro100** [comment]
This is resolved, but we will have to add excluded files ongoing as we find them
