### ISSUE TITLE
Setup Alpaca

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#108]
As a developer I would like to setup Alpaca in the backend so future developers can easily work on top of it

Note:
- For the API keys, reach out to me and I'll create them for you - Alessandro

**Acceptance Criteria**
- The Alpaca SDK is setup
- We are able to make a successful test call to an Alpaca endpoint
- It is setup as shown in the software class diagram (Facade)

**Comment by DPigeon** [comment]
For now, Alpaca has been setup properly with my Alpaca`s secret keys for testing. Three different endpoints were to test locally. Everything is setup as shown in the class diagram. However, we still have to setup the Order Decorators. I am still unsure if we want to write the basic methods that will be used for the Order Decorators now or if we just want a simple Order Decorator setup like what was done by @razine-bensari and @amansourcoveo already in the iex & setup backend architecture branch.

**Comment by razine-bensari** [comment]
We can leave order decorator methods for now, because for the first set of features/ release 1 we will not be making orders just yet.

Once we work on the feature that needs us to create order, we will implement the methods related to orders decorators.

WDYT?

**Comment by DPigeon** [comment]
> We can leave order decorator methods for now, because for the first set of features/ release 1 we will not be making orders just yet.
> 
> Once we work on the feature that needs us to create order, we will implement the methods related to orders decorators.
> 
> WDYT?

Alright I agree. They are setup for now anyway and the files are made.
