### ISSUE TITLE
Display Stock Price

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#117]
As a user I want to be able to see the current price of a stock so I see if I want to buy or sell

**Acceptance Criteria**

- Display current price of the stock 
- Display the daily change of the stock
- If the daily change is up, the text must be green
- If the daily change is down, the text must be red
- Must have unit tests for the color of the text
- Stock values must reflect real life values
- An e2e test is written

![Screen Shot 2020-10-16 at 6 25 44 AM](https://user-images.githubusercontent.com/18631060/96247687-777b6600-0f78-11eb-9725-6cbf5086632a.png)

**Comment by lindsaybangs** [comment]
Looks good! Consider this accepted on my side 👍
