### ISSUE TITLE
Replace all sensitive api key values by placeholder in test files

### ISSUE THREAD

**Issue by razine-bensari** [DPigeon/Money-Tree#128]
When it comes to testing, it is sometime preferable to not Mock the client dependency and simply instantiate it. to do that and make api calls, we need to provide API keys and secret keys. As of now, in the test folder they are hardcoded.

the scope of this issue is to remove all hardcoded api keys and sensitive information and replace them with place holders to enhance the security of our api and to be able to deploy in production before releasing.

**Comment by Alessandro100** [comment]
This was fixed
