### ISSUE TITLE
Show user owned stocks their quantity

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#13]
As a user I would like to easily see what stocks I own and the quantity

**Acceptance Criteria**
- User can view the name and symbol of stocks they own
- User can view the quantity of the stock they own

![image](https://user-images.githubusercontent.com/18631060/108726554-8d380380-74f5-11eb-9d56-6733a6898cba.png)

**Comment by lindsaybangs** [comment]
Accepted 💯
