### ISSUE TITLE
Create endpoints for create account

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#135]
As a developer I want to create backend endpoints to handle creating an account

**Acceptance Criteria**
- [x] When given data (email, username, password, first name, last name) it will create a user node in our database
- [x] Must return error if email / username exists exists
- [x] When the user gets an Alpaca key, update the users information in the database **
- [x] Unit tests are written
- [x] The passwords must be encrypted in our database

**Comment by razine-bensari** [comment]
![ssd_flow_createUser](https://user-images.githubusercontent.com/34013446/98755161-0754da00-2396-11eb-99f4-74c20d4af8de.png)

**Comment by razine-bensari** [comment]
Here is a quick draft SSD that the FRONT END will need to conform in order process the user creation

**Comment by DPigeon** [comment]
After starting implementing this story, I realized that #122 was needed before. If we don't want to write ugly and messy code, we need #122 first.

**Comment by Alessandro100** [comment]
If 'sendEmailConfirmation' means that the user will get an email and will have to confirm his account, then we wont be doing that. We are building an MVP
