### ISSUE TITLE
Setup CORS rules in the backend

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#136]
As a developer I want cors rules enable to access the backend for development

**Acceptance Criteria**
- The frontend can make calls to the backend running on localhost with no CORS extensions

**Comment by DPigeon** [comment]
Hey @razine-bensari I think this story should also make it so that only localhost can send requests to the backend. What do you think?

**Comment by razine-bensari** [comment]
yeah, that is exactly it! working on it!
