### ISSUE TITLE
Create form logic for login page

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#138]
Form Constraints:
- User must enter a unique email address **(needs backend)**
- User must enter a strong password of at least 7 characters
- User must enter a unique username (think of this as a twitter handle) **(needs backend)**

**Acceptance Criteria**
- Form logic for login
- Form logic for create account
- If there are errors -> must show an error on the page
- If form is ok, will call the backend endpoint (create account / login)
- Unit tests are written
- System tests are written

![image.png](https://images.zenhubusercontent.com/5e160ea2cbe5be5b659938e7/c9f76a4f-587b-4e9e-a03d-18d79a512d57)

**Comment by wltrf** [comment]
#135 and #139 will be done soon :)
