### ISSUE TITLE
IEX Cloud API keys

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#141]
As a developer I want to optimize IEX Cloud usage to better scale

Todo: Discuss best IEX practices

**Acceptance Criteria**
- Use IEX sandbox environment in tests (or mock them)
- Analyze how we can reduce our IEX usage
- Remove 'news' and 'key statistics'

**Comment by razine-bensari** [comment]
`This is what you need to add to you environment variables

#For MoneyTree
export ALPACA_KEY_ID="PKZJK3IXQ4JZAWCBDSRX"
export ALPACA_SECRET_ID="SA5sYIYR58AukN8NKpdGkQZSCvOCoTXYgyjuaoUe"
export IEXCLOUD_PUBLISHABLE_TOKEN_SANDBOX="Tpk_41cea3476f55437aa0a7ff89162ea9c4"
export IEXCLOUD_SECRET_TOKEN_SANDBOX="Tsk_072d4c09f38148a9b68b748b38fad53c"

export IEXCLOUD_PUBLISHABLE_TOKEN_PROD=""
export IEXCLOUD_SECRET_TOKEN_PROD=""

export NEO4J_USERNAME="neo4j"
export NEO4J_PASSWORD="stonecap"


`
