### ISSUE TITLE
Setup image storing service

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#145]
As a developer I would like to have a image storing service to have custom images in the application

**Acceptance Criteria**
- Setup Amazon S3 (or other service) (or look into if we want something free https://min.io/ but has to be hosted)
- Setup 'edit profile' endpoint
- Tests

**Comment by abdulmansour** [comment]
Scenario: a user uploads profile_pic1, then 1 week later changes it to profile_pic2, what do we do with profile_pic1? do we delete profile_pic1 or keep both images stored?

Resolution: Delete old picture, store new picture, update avatarUrl in db.

**Comment by abdulmansour** [comment]
Test in progress, having issues with mocking services, will require some assistance @Alessandro100 @DPigeon @razine-bensari 

Here is current progress:

**Comment by DPigeon** [comment]
> Task 90%, required test is left to be completed and is in progress, having issues with mocking services, will require some assistance @Alessandro100 @DPigeon @razine-bensari

We can have a call today about it.
