### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#146]
As a developer I would like to see API documentation to speed up development time

**Acceptance Criteria**
- Have a place to see / test API calls and what they return

**Comment by wltrf** [comment]
Let's try to follow the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification)

Here's a list of [implementations](https://github.com/OAI/OpenAPI-Specification/blob/master/IMPLEMENTATIONS.md)

[SwaggerHub](https://swagger.io/tools/swaggerhub/) is the best tool with a web GUI but comes at a cost for more than one user, so it could be a solution if we decide to use the common email that we have for the project. It allows for design, documentation and more all hosted.
Similarly we can download the [swagger open source editor](https://github.com/swagger-api/swagger-editor) and host the docs ourselves
![Screenshot from 2020-11-27 09-51-03](https://user-images.githubusercontent.com/33789241/100460953-14f8a800-3096-11eb-8e7a-57d0fd905a1b.png)


Another one I found is the [springdoc-openapi Java library](https://github.com/springdoc/springdoc-openapi). It can be added as a maven dependency and it generates at runtime the api docs by looking at spring configuration and stuff. The disadvantage is we can't really design with this one, it's mostly to automate the docs generation (similar to javadocs)
![Screenshot from 2020-11-27 09-43-32](https://user-images.githubusercontent.com/33789241/100460372-0fe72900-3095-11eb-9139-4a5004dcfb52.png)

Proposed by @razine-bensari is [slate](https://github.com/slatedocs/slate) which is documentation written in mardown. It allows for design of the api.
![Screenshot from 2020-11-27 09-44-28](https://user-images.githubusercontent.com/33789241/100460451-2beaca80-3095-11eb-8100-a037c0dd37ae.png)

Each have their own advantages and disadvantages. I think it comes down to preference so I could test them and maybe share a demo/tech session where we discuss the different solutions.


At first look, and from the research, I personally have a preference for the swagger-editor option

**Comment by wltrf** [comment]
Let's have a tech share friday Dec 4th where I will demo the options and we can discuss/decide which one we go with.

**Comment by wltrf** [comment]
generator has been selected for simplicity and to ensure our docs are always in sync with the actual code. We can still use the swagger-editor by importing our yml file available at /api/v1/v3/api-docs which allows for design and code generation.
