### ISSUE TITLE
CI Workflow Improvements

### ISSUE THREAD

**Issue by wltrf** [DPigeon/Money-Tree#154]
The current ci.yml workflow is slow and could be improved.

1. Split ci.yml into 2 files: ci_frontend.yml and ci_backend.yml
This would allow us skip one of the ci if there are no changes in that particular folder.
The way this works is by specifying a path for the action trigger.
e.g. for ci_backend.yml
```yml
on:
    pull-request:
        paths:
        -'./backend/**'
```
see this [link](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) for more information.

2. We currently run the same maven goals multiple times. The way maven works is different than npm in that maven will call all goals from the lifecycle up and until the specified goal while npm just runs the specific script.
See this [link](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)
https://github.com/DPigeon/Money-Tree/blob/df28d283dd6109af2e28427bce1aed34df5d34d1/.github/workflows/ci.yml#L96-L107
The code above will run the following goals:
- validate
- compile
- test
- package
- verify
- **install**
- **clean**
- validate
- compile
- **test**
- validate
- compile
- test
- package
- **verify**

This is clearly redundant and could be replaced by a single step which calls `mvn clean verify`

3. This isn't a performance issue, but more of a simplification question: Why do we use the ./mvnw instead of using the mvn binary provided by github actions i.e. use mvn instead of ./mvnw

** ACCEPTANCE CRITERIA **
- pipeline split into two files, see 1.
- pipeline runs only if a change in the specific folder, see 1.
- there is a single maven call for backend, see 2.
- there is no instance of mvnw (wrapper) only the mvn (binary), see 3.

**Comment by wltrf** [comment]
@DPigeon thoughts, comments?
@razine-bensari am i wrong on the maven stuff?

**Comment by DPigeon** [comment]
Yes everything inside this is good! We can improve the pipeline for sure.
1. Totally agree
2. Redundant for sure. However how are we going to validate if the cache exists with a single mvn clean verify command?
3. The mvn command was not working in the cicd environment when I first worked on it.

**Comment by wltrf** [comment]
Cache is done automatically in the step before. We are currently the non wrapper mvn for the sonarscanner step, so it works.
