### ISSUE TITLE
Display user portfolio value over time

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#16]
As a user I would like to know my past and present value of my portfolio to determine how I was doing

ex: If I'm an investor and in January 2020 I had 1000, and over the corse of 3 months I made 500$ (total of 1500$) I want to see a time series graph of that increase

Similar to the wealthsimple profile graph

**Acceptance Criteria**
- User will be able to see a time-series graph of their portfolio value
- User will be able to modify the date range from (all-time, 1 year, 3 months, 1 month, 1 week, 1 day)
- User will be able to view other user's profile graph

![image](https://user-images.githubusercontent.com/18631060/108724155-04b86380-74f3-11eb-87a5-2551686bfc74.png)

**Comment by lindsaybangs** [comment]
Accepted 👍
