### ISSUE TITLE
Add Persistent Test DB to Facilitate Tests

### ISSUE THREAD

**Issue by wltrf** [DPigeon/Money-Tree#161]
1. Have a neo4j service running at all times on dev env.
```bash
docker run \
    --publish=10000:7474 --publish=10001:7687 \
    --volume=home/neo4j/test/data:/data \
    neo4j
```

2. change password

Note: make sure the tests perform a cleanup of the database to restore what has been changed otherwise a test like create accout will fail on second run since the user will already exist

** ACCEPTANCE CRITERIA **
- a neo4j browser cient is hosted on dev.money-tree.tech:10000 and the password is not the default
- a test neo4j db is running on dev.money-tree.tech:100001 via bolt
- optional (another story can be created): change existing tests to use that db instead of mocking.

**Comment by DPigeon** [comment]
A container could be started and always run like mentioned in this story. We could also schedule a job that runs a "check script" on the dev VM every hour. If would do this:
- If neo4j container is up, do nothing
- Otherwise, start it

That way we don't have to check manually if the image goes down for some unexpected reasons. What do you think?

**Comment by wltrf** [comment]
No need to schedule a job, the docker service can handle that. We just need to -d (detach) and --always ([restart-policy](https://docs.docker.com/config/containers/start-containers-automatically/)). Can you run the following command on the dev vm:
```bash
docker run -d --always \
    --publish=10000:7474 --publish=10001:7687 \
    --volume=home/neo4j/test/data:/data \
    neo4j
```

**Comment by DPigeon** [comment]
> No need to schedule a job, the docker service can handle that. We just need to -d (detach) and --always ([restart-policy](https://docs.docker.com/config/containers/start-containers-automatically/)). Can you run the following command on the dev vm:
> ```bash
> docker run -d --always \
>     --publish=10000:7474 --publish=10001:7687 \
>     --volume=home/neo4j/test/data:/data \
>     neo4j
> ```

Cool I did not know that. Will do!

**Comment by razine-bensari** [comment]
Guys, nice addition, sorry to be so late, I never receive notifications from github,

**Comment by DPigeon** [comment]
The test DB should be up [here](http://dev.money-tree.tech:10000/browser/).

**Comment by wltrf** [comment]
I changed the password, see slack #secret-sharing for password. 

The only thing is when we open up the neo4j browser, the default port for bolt is 7687, but for the test db we use 10001. If we don't want to manually change it everytime, we can set a configuration so instead of the previous command, let's run the following (added --env line, edited --restart flag)
```bash
docker run -d --restart always \
    --publish=10000:7474 --publish=10001:7687 \
    --volume=/home/neo4j/test/data:/data \
    --env NEO4J_dbms_connector_bolt_advertised__address=:10001 \
    neo4j
```
@DPigeon

**Comment by wltrf** [comment]
ACCEPTANCE CRITERIA met, closing issue. 
![Screenshot from 2020-11-23 11-37-48](https://user-images.githubusercontent.com/33789241/99989238-621c0780-2d80-11eb-8d18-5929f5c2cf67.png)
