### ISSUE TITLE
Change Existing Tests to Use Test DB Instead of Mocking.

### ISSUE THREAD

**Issue by wltrf** [DPigeon/Money-Tree#165]
As a developer I would like to use test db instead of mocking data for better tests

See #161 

**Acceptance Criteria**
- Change the tests to not use mocking stuff, but rather use a test db

**Comment by wltrf** [comment]
#180 related

**Comment by DPigeon** [comment]
Note that for this story, we`ll be using the UAT database for tests [here](http://dev.money-tree.tech:7474/browser/).

**Comment by wltrf** [comment]
^ additional info on comment above, this is because we cap our memory limit on the vm when running 2 db instances. We can use different schemas inside the same dbms instead.

**Comment by DPigeon** [comment]
Yes so for more information, we tried running 2 neo4j instances but since we're already running the backend and client, we peaked 95% memory. See this graph below for the uat VM.
![2222](https://user-images.githubusercontent.com/37888675/101649481-ecaf6880-3a08-11eb-9448-8e86bc928617.png)

The sudden drop is one of the neo4j instances shutting down due to a lack of memory.

**Comment by wltrf** [comment]
**Summary**
1. Can't run 2 dbms due to vm memory limitations
2. Can't create a separate db inside the existing dbms due to it being an "enterprise" feature

Solution: Use the uat database, and make prefix users with test.

**Comment by wltrf** [comment]
Note: We added a 1G swapfile to the vm to alleviate memory and fix some crashes and issues.

**Comment by DPigeon** [comment]
Hey @wltrf and @razine-bensari are the two branches you worked on for this issue the integrated together? It seems like this branch made from Walter https://github.com/DPigeon/Money-Tree/tree/feature/%23165-test-db and this PR made from Razine https://github.com/DPigeon/Money-Tree/pull/221 have no link between them.

**Comment by razine-bensari** [comment]
@DPigeon  @wltrf  was exploring on how to have an internal db running with the test for integration testing. He proposed to simply connect to the UAT db instead as having the internal seems to not work because of emmory  limitations.

The pr I made is to use the UAT db in integration testings

**Comment by DPigeon** [comment]
Ok thanks for clarifying!
