### ISSUE TITLE
View user transactions

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#17]
As a user I would like to see all my transactions and other user's transactions to get information on new stocks while viewing my history

**Acceptance Criteria**
- User will be able to see **their** own transactions of **completed** buy / sell orders
- User will be able to see **their** own transactions of **pending** buy / sell orders
- User will be able to see **other user's** transactions of **completed** buy / sell orders
- Transaction information must contain: date transaction completed, company name, average purchase cost per share, number of shares bought, total purchase cost,  order type (buy/sell), state if it's pending
- On clicking on the transaction, should redirect user to the stock detail page

Example of the information:
September 14 2020
Apple (AAPL)
250$ cost per share
5 shares
1250$ total cost
buy
pending

**Comment by lindsaybangs** [comment]
Accepted!
