### ISSUE TITLE
Generic Update User Endpoints

### ISSUE THREAD

**Issue by DPigeon** [DPigeon/Money-Tree#174]
As a user, I want to be able to update my information so that others can see my new updated information on my profile.

We have made an endpoint for adding (updating) an Alpaca key when a user registers. In the future, we will need a more generic function that updates any parameters in a user. This story focuses on refactoring any update methods done and replace all calls by this new user.update() method.

**Acceptance of Criteria:**
- [ ] Update method works for any user field
- [ ] Unit tests are updated if needed
- [ ] Replace all the old update calls with this one
- [ ] Update the frontend endpoint

**Comment by abdulmansour** [comment]
@Alessandro100 

Here is the User class defined in the backend; [link](https://github.com/DPigeon/Money-Tree/blob/dev/backend/src/main/java/com/capstone/moneytree/model/node/User.java)

A PUT method already exists, which takes care of updating the user's profile image only atm; [link](https://github.com/DPigeon/Money-Tree/blob/c9075cdf0ac63861f11faf3ce41bf6c65c3f3bee/backend/src/main/java/com/capstone/moneytree/controller/UserController.java#L107). The method should be upgraded to receive a User object from the frontend which correspond to the defined User object above, and update the User accordingly (simply saving the incoming object, which will update existing user).

Does that work for this issue?

**Comment by Alessandro100** [comment]
@abdulmansour 

It's great that this method exists, but yes we will have to upgrade this method to include other user parameters such as: firstname, bio, etc. I saw that there is extra logic to saving an image, do you think we should have a specific endpoint just for updating images?

PUT /users/{id} for generic update
PUT /users/profile-image/{id} for updating images

thoughts?

**Comment by abdulmansour** [comment]
Yes I think that would make more sense aswell
