### ISSUE TITLE
Add error handling object in the frontend

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#175]
As a developer I would like a consistent error model to better display errors

**Acceptance Criteria**
- An error model is created in the frontend that mirrors the backend error model
- The model is implemented

**Comment by razine-bensari** [comment]
This is what the error json looks like from backend api to front endL:

`{
  "status": "BAD_REQUEST",
  "timestamp": null,
  "message": "Illegal argument(s) in the URI",
  "debugMessage": "Invalid address format `bolt://IP_REMOTE_NEO4J:7687`"
}`

**Comment by razine-bensari** [comment]
`{
  "status": "BAD_REQUEST",
  "timestamp": null,
  "message": "Illegal argument(s) in the URI",
  "debugMessage": "Invalid address format bolt://IP_REMOTE_NEO4J:7687"
}`

**Comment by razine-bensari** [comment]
<img width="520" alt="Screen Shot 2021-01-09 at 12 37 02 PM" src="https://user-images.githubusercontent.com/34013446/104104636-60969800-5277-11eb-9120-f4d3918a85bd.png">
