### ISSUE TITLE
Implement Analytics

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#177]
As a developer I would like to collect analytics so I can see where to improve the application

**Acceptance Criteria**
- Implement the solution that is proposed in the google doc
- Test it to assure that its implemented in the prod environment (include it in uat as well?)

**Comment by DPigeon** [comment]
To keep the analytics key safe and secret, we could use this approach: https://pumpingco.de/blog/environment-variables-angular-docker/

We can go deeper into the subjects later.
