### ISSUE TITLE
Investigate / Optimize IEX Cloud API calls

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#179]
As a developer I would like to optimize the IEX Cloud endpoint in the backend so I can make more calls

**Acceptance Criteria**
- Find a solution to reduce the amount of messages used in the IEX Cloud

<br>
<br>

Potential Solutions / Discussion Notes

1. ~~Take out a mortgage and pay for IEXCloud~~
2. Mock api/service as proposed by lindsay (wiremock)
3. Some sort of Proxy server
4. Store stock info in database as a mean of caching.
5. Not use /batch calls which are expensive

**Aditionnal Optimizations**
Use cache when making calls, from client to backend and/or from backend to iexcloud
https://web.dev/cache-api-quick-guide/
https://spring.io/guides/gs/caching/

The one below is paid, but we could implement something similar.
https://iexcloud.io/cloud-cache/

**Comment by wltrf** [comment]
**Potential Solutions / Discussion Notes**

1. ~~Take out a mortgage and pay for IEXCloud~~
2. Mock api/service as proposed by lindsay
3. Some sort of Proxy server
4. Store stock info in database as a mean of caching.
5. Not use /batch calls which are expensive

**Aditionnal Optimizations**
Use cache when making calls, from client to backend and/or from backend to iexcloud
https://web.dev/cache-api-quick-guide/
https://spring.io/guides/gs/caching/

The one below is paid, but we could implement something similar.
https://iexcloud.io/cloud-cache/

**Comment by wltrf** [comment]
https://query1.finance.yahoo.com/v8/finance/chart/AAPL

**Comment by wltrf** [comment]
https://github.com/iexg/IEX-API/issues/718
^ issue from a guy discussing price issue for his app. The IEXCloud guys suggest to use some sort of caching (multiple solutions vaguely stated)

for insight only, not very useful

**Comment by wltrf** [comment]
https://iexcloud.io/docs/api/#company
https://iexcloud.io/docs/api/#quote

**Comment by Alessandro100** [comment]
Solution: Remove expensive calls and we'll deal with historical data later through Yahoo finance API
