### ISSUE TITLE
Investigate how to have a filled db for testing in the frontend / backend

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#180]
As a developer I would like to access a remote database for easier time testing

**Acceptance Criteria**
- The commands for the backend are are stated under
- Ability to establish connection to remote database from frontend / backend
- update readme

mvn spring-boot:run (uses remote db - uat environment/application.properties file)
mvn spring-boot:run -Dspring.profiles.active=local (uses local db/application-local.properties file)
mvn spring-boot:run -Dspring.profiles.active=prod (uses prod db/application-prod.properties file)

**Comment by razine-bensari** [comment]
mvn spring-boot:run (uses remote db - uat environment/application.properties file)
mvn spring-boot:run -Dspring.profiles.active=local (uses local db/application-local.properties file)
mvn spring-boot:run -Dspring.profiles.active=prod (uses prod db/application-prod.properties file)
