### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#19]
As a user I would like to add information to my account to give the app a personalized experience

**To discuss**
- Should the user's password be forced to be stronger since we are dealing with money? -> yes (basic for now)

**Acceptance Criteria**
- User must enter a unique email address
- User must enter a strong password of at least 7 characters
- User must enter a unique username (think of this as a twitter handle)
- User can enter an optional biography
- User can upload a personal image as a profile picture
- If the user does not upload a personal image, they will be assigned a default profile image
- If the user enters bad information there should be error messages that are displayed

**Comment by lindsaybangs** [comment]
Reviewed and accepted on Monday, Feb 1st, 2021 at 2:30 PM
