### ISSUE TITLE
[BUG] Signup Password Validation

### ISSUE THREAD

**Issue by wltrf** [DPigeon/Money-Tree#197]
**Describe the bug**
1. Signup Password validation doesn't detect some symbol characters such as:  / | \ ( ) - _ ^ + = ~ < > " :
2. Signup Password validation breaks when going back and forth between password_1 and password_2 boxes

**To Reproduce**
1. Go to http://dev.money-tree.tech/
2. Click on signup_password_1 box
![Screenshot from 2020-12-09 10-25-01-pass1](https://user-images.githubusercontent.com/33789241/101649548-0486ec80-3a09-11eb-99b8-f8f7afcc4c21.png)

3. Enter password in box 1 with at least 8 chars including letters, numbers and one of the symbol characters mentioned above
4. Click on signup_password_2 box
![Screenshot from 2020-12-09 10-25-01-pass2](https://user-images.githubusercontent.com/33789241/101649956-719a8200-3a09-11eb-9b2f-3b6944d2dd8c.png)

4. See error 1.
![Screenshot from 2020-12-09 10-28-55](https://user-images.githubusercontent.com/33789241/101649985-752e0900-3a09-11eb-83e3-6b728835f080.png)

5. Enter different password in box 2
6. Change password in box 1 to match box 2
7. See error 2. (note that many different steps of going back and forth between box 1 and box 2 produce this error)
![Screenshot from 2020-12-09 10-32-54](https://user-images.githubusercontent.com/33789241/101650595-19b04b00-3a0a-11eb-9836-a2673c762d51.png)

**Expected behavior**
1. Should either accept all symbols mentioned and probably more, or should specify which symbols are accepted.
2. Validation should reflect what is contained in password boxes.

**Desktop (please complete the following information):**
 - OS:
![Screenshot from 2020-12-09 10-39-08](https://user-images.githubusercontent.com/33789241/101651211-cee30300-3a0a-11eb-91cb-d2ac1bb20a8f.png)

 - Browser:
![Screenshot from 2020-12-09 10-38-16](https://user-images.githubusercontent.com/33789241/101651134-b70b7f00-3a0a-11eb-88bb-2b71ddf1792e.png)

Bug reported by @wltrf 
#138 #186

**Comment by EspressoCode** [comment]
I will fix this bug soon today, a regex change should fix.
