### ISSUE TITLE
[BUG] Unique Email/Username Validation

### ISSUE THREAD

**Issue by wltrf** [DPigeon/Money-Tree#198]
**Describe the bug**
The /users/create-user endpoint doesn't check if an email is unique or if a username is unique

**To Reproduce**
PREREQ: A local backend/db combo running locally
1. Open Terminal and run the following command (or run in postman):
2. curl --location --request POST 'http://localhost:8080/api/v1/users/create-user' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "hello.friend@gmail.com",
    "username": "hello",
    "password": "password123",
    "firstName": "hello",
    "lastName": "friend"
}'
3. curl --location --request POST 'http://localhost:8080/api/v1/users/create-user' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "hello.friend@gmail.com",
    "username": "hello2",
    "password": "password123",
    "firstName": "hello",
    "lastName": "friend"
}'
4. curl --location --request POST 'http://localhost:8080/api/v1/users/create-user' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "hello.friend2@gmail.com",
    "username": "hello",
    "password": "password123",
    "firstName": "hello",
    "lastName": "friend"
}'
5. See error (step 3 and 4 return ok). Alternatively, browse to http://localhost:7474/browser and see the three users created

**Expected behavior**
Step 3 and 4 should return errors since they use a non unique email and non unique username respectively.

**Desktop (please complete the following information):**
 - OS:
![Screenshot from 2020-12-09 10-39-08](https://user-images.githubusercontent.com/33789241/101653913-e40d6100-3a0d-11eb-88c3-0e52b344941c.png)
- $ curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
- Postman v7.36.0

**Additional context**
This was previously reported in a PR review, but has been overlooked/slipped through
![Screenshot from 2020-12-09 11-07-13](https://user-images.githubusercontent.com/33789241/101654959-14a1ca80-3a0f-11eb-8869-ab4b3e25cf53.png)
The code is now slightly different (in UserValidator and doesn't use && explicitly), but the issue is the same idea.

Bug reported by @wltrf 
#135 #153

**Comment by DPigeon** [comment]
I remember working on this a while back. We had a discussion on this. So we want either the email OR username to match in that case:
`if (email.equalsIgnoreCase(user.getEmail()) || username.equalsIgnoreCase(user.getUsername())`

I'll try to have this done soon. It should not be too long to fix.

**Comment by wltrf** [comment]
Should also fix the tests as if they didn't pick this up, they are not checking this correctly.
