### ISSUE TITLE
Account Login

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#20]
As a user, I would like to access my account in a secure manner to access my information

**To discuss**
- Should the user's session expire after x amount of time? 

**Acceptance Criteria**
- The user must enter their email address or username as well as the corresponding password to access their account information
- If the information is not correct, an error message must appear
- Once the user is logged in, they must remained logged in even after switching pages (cookies)

**Comment by lindsaybangs** [comment]
Reviewed and accepted on Monday, Feb 1st, 2021 at 2:30 PM
