### ISSUE TITLE
Fix backend code smells

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#207]
As a developer I would like to fix the code smells so the code stays clean and efficient

Question:
- Should we make refactoring activity stories like this? Or more precise? Yes, fine for hanging code smells not fixed in PRs.

**Acceptance Criteria**
- All the backend code smells are addressed

**Comment by wltrf** [comment]
![Screenshot from 2021-01-24 08-44-35](https://user-images.githubusercontent.com/33789241/105632315-6fa54a80-5e20-11eb-9030-c4f706b43350.png)
