### ISSUE TITLE
Account Logout

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#21]
As a user I would like to logout of my account so that the next person to access the website won't have my information

**Acceptance Criteria**
- The user should have the ability to logout of the application
- They will be redirected to a stateless page (initial page)
- Once logged out, they should not be able to view any of their account information

**Comment by lindsaybangs** [comment]
Reviewed and accepted on Monday, Feb 1st, 2021 at 2:30 PM
