### ISSUE TITLE
Search a user by username

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#23]
As a user I would like to search for another user by username

**Acceptance Criteria**
- When searching for a user, the textbox should attempt to autofill / recommend existing users
- If no users are found in the search, return result 'No users matching'
- When searching for a user, in the autofill box, it should display the user's profile picture and name
- When the searched user is selected, I would like to see more information on that user

![Screen Shot 2020-09-15 at 9.52.26 AM.png](https://images.zenhubusercontent.com/5e160ea2cbe5be5b659938e7/9b0e5943-9ca1-41bb-b001-b10a706ba5a2)

**Comment by lindsaybangs** [comment]
accepted 🤖
