### ISSUE TITLE
Display real values in owned stock (stock detail page)

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#233]
As a user I would like to see 

Discussion:
- I think we should load the user's portfolio as they login. Any changes will be updated through the webhook

Note:
- We will have to implement webhooks to get the trades in real time (later)

**Acceptance Criteria**
- Load the user's owned stocks on login
- When the user goes on the stock detail page, it will display to them their actual stock data (If it exists)

Exists
![image.png](https://images.zenhubusercontent.com/5e160ea2cbe5be5b659938e7/7f74d6e8-670b-4a8c-947b-519e2cd84a37)

Doesn't exist
![image.png](https://images.zenhubusercontent.com/5e160ea2cbe5be5b659938e7/d0fbd40c-e95e-4112-a2f7-752466fd5e08)

**Comment by Alessandro100** [comment]
In this story you will:
- Implement the OWNS relationship
- Refactor Fulfilled relationship
- Create the stock node objects

**Comment by EspressoCode** [comment]
The scope of this story was increased since we will have to refactor the implementation and add new backend endpoints.
