### ISSUE TITLE
Implement trade update webhook frontend

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#234]
As a user I would like to see my trade statuses update in real time

**Acceptance Crtieria**
- When a user logs in, connect them with a webhook to the backend so receive trade updates

Note: This will be done in sprint 7

**Comment by DPigeon** [comment]
Here is some info about the ws endpoint on the backend:
- Connect with a SockJS & STOMP websocket client on the frontend
-  **Local** profile endpoint to connect to: `http://localhost:8080/api/v1/ws`
- **Dev** profile endpoint to connect to: `https://dev.money-tree.tech/api/ws`
- **Prod** profile endpoint to connect to: `https://money-tree.tech/api/ws`
- Subscribe to the user's channel through `/queue/user-{userId}`
- Send the userId as message content through `/app/trade/updates`

Then you should be able to listen to the Alpaca streams. It should stream the client order ID when an order is filled.
