### ISSUE TITLE
View number of followers / people who follow the user + detail user list

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#25]
As a user I would like to know the number of followers / people I'm following as well as a detailed list of who they are to better know my social circle

**Acceptance Criteria**
- User must be able to see the number of followers they have
- User must be able to see the number of people they follow
- User must be able to see the number of followers other users have
- User must be able to see the number of people other users have
- When clicking on the number of (followers / people they follow) they can see a list of their username and profile
- When clicking on a user from this list, they will be brought to their profile page

![Screen Shot 2020-09-15 at 10 19 54 AM](https://user-images.githubusercontent.com/18631060/93222504-065c4f00-f73d-11ea-9ef2-aed36b0dcceb.png)

**Comment by lindsaybangs** [comment]
Accepted 🥇
