### ISSUE TITLE
Change backend endpoints to use HTTPS

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#250]
As a user I would like to make backend calls securely so non of my data is stolen

**Acceptance Criteria**
- When making requests on UAT or PROD, assure that the api endpoint is done with HTTPS instead of HTTP
- Change the URL in the frontend

**Comment by DPigeon** [comment]
FYI: When we try to login we get this error
`
polyfills.35a5ca1855eb057f016a.js:1 Mixed Content: The page at 'https://dev.money-tree.tech/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dev.money-tree.tech/api/users/'. This request has been blocked; the content must be served over HTTPS.
`

**Comment by wltrf** [comment]
https://www.sslshopper.com/article-most-common-openssl-commands.html
