### ISSUE TITLE
View basic profile information

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#26]
As a user, I would like to view my profile information or another user's profile information

**Acceptance Criteria**
- View my own profile picture
- View my own biography
- View my own username
- View my own cover photo
- View my own name
- View other user profile picture
- View other user biography
- View other user username
- View other cover photo
- View other name

![image](https://user-images.githubusercontent.com/18631060/108722842-92934f00-74f1-11eb-8039-8c2ffa5f036c.png)

**Comment by lindsaybangs** [comment]
Accepted 🥇
