### ISSUE TITLE
Create Account Endpoint returning a 500

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#263]
**Describe the bug**
When the user tries to make an account they get a 500 error coming from the backend
"org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected at most 1"

**To Reproduce**
1. Go to login page
2. Try to make a new account
3. See error in console

**Expected behavior**
There should be no error and the user is redirected to alapca

Bug reported by @Alessandro100

**Comment by wltrf** [comment]
Need more information to reproduce. Is this local, dev, or prod?

**Comment by Alessandro100** [comment]
This happens on all environments

**Comment by Alessandro100** [comment]
bug was due to old accounts being duplicated. This should not be an issue going forward
