### ISSUE TITLE
Add the stock graph in the frontend

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#267]
As a user I would like to see the historic prices of a stock to make better future decisions

Note:
- This story is blocked until the backend story is done
- The graph will be generated through a library

**Acceptance Criteria**
- The user is able to see [1 day, 5 days, 1 month, 6 months, 1 year, 5 years, max years] prices of a stock
- If the user hovers over the graph with their mouse, they will be able to see the price

![image.png](https://images.zenhubusercontent.com/5e160ea2cbe5be5b659938e7/21b829f1-a10f-4d01-b94b-66e32c2fffd0)

**Comment by Alessandro100** [comment]
@wltrf you can give Marwan a sample data return so he isn't blocked

**Comment by Alessandro100** [comment]
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

**Comment by razine-bensari** [comment]
https://echarts.apache.org/en/index.html

**Comment by wltrf** [comment]
Link to yahoo chart frontend: https://ca.finance.yahoo.com/chart/AAPL
Link to yahoo chart data: https://query1.finance.yahoo.com/v8/finance/chart/AAPL

First link is to help you understand the data.
Second link is the data. Some data is not really useful, depending on how much info we want to display. The price data you want to look at is under results.0.indicators.quote.0.close and the time data you want to look at is under results.0.meta.timestamp

There's also the idea of data granularity. You can see the different ranges available and the current range in use. Let me know if you need any help to understand.

**Comment by wltrf** [comment]
You will be able to switch from the yahoo endpoint to the endpoint below once #295 is merged.

![Screenshot from 2021-02-18 15-49-50](https://user-images.githubusercontent.com/33789241/108419829-020ef300-7201-11eb-9023-9ede1932f50c.png)

**Comment by Alessandro100** [comment]
@marwan-ayadi note this story has a system test attached

**Comment by wltrf** [comment]
@marwan-ayadi regarding the the issue about some null datapoints, with apache echart there's an option to connect through nulls (ignore them basically) 
https://echarts.apache.org/en/option.html#series-line.connectNulls
![Screenshot from 2021-02-23 20-26-07](https://user-images.githubusercontent.com/33789241/108931385-928c6f80-7615-11eb-9a79-4e9f3319cc9c.png)
