### ISSUE TITLE
Add additional social information to the stock endpoint

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#268]
Notes
- "Top Investors who own this stock": Return the profile of user's who's scores are in the top 10%
- "Followers who also own this stock": Return the profile of user's who the current user follows AND own the stock
- "People who own this stock also own": Return the top 5 stocks that people who own this 
        - example: let's say 5 people own AAPL, and 4/5 of those people also own MSFT, then it would return [MSFT 80%]

Extra Notes
- These queries should be neo4j efficient, we can discuss the functionality of them
- This story might be done later in the sprint as we will get the information later (followers, updating scores, etc)

**Acceptance Criteria**
- Add "Top Investors who own this stock" to the GET stock endpoint
- Add "Followers who also own this stock" to the GET stock endpoint
- Add "People who own this stock also own" to the GET stock endpoint

**Comment by DPigeon** [comment]
Part 1 and part 2 were merged. Is there a part 3 coming from @abdulmansour ?
