### ISSUE TITLE
How to return all users for the user search bar

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#275]
When the user will search for people to follow in the search bar, how will the frontend get that data? Are we simply going to return all the users (with restricted parameters)? When will this data be loaded? How often?

**Acceptance Criteria**
- All the questions above are answered
- If there is a solution thats needed, that solution is implemented

**Comment by abdulmansour** [comment]
@Alessandro100 
As discussed in today's meeting, we will configure a search users endpoint which will return one of the following:

- returns list of all stored users (frontend receives all users beforehand and simply filters list based on searchbox query); benefit: single http request | con: fetches all users stored in db
- returns list of users based on search query; calls endpoint and returns results as the users types into the searchbox; benefit: smaller response per http request | con: large # of http requests (5-10 average/user); should we set a max users return count/http request?

*A user would be condensed to only the essentials: id, firstName, lastName, username, avatarURL

**Comment by abdulmansour** [comment]
This is sample response, a list of object; each object containing the following properties: firstName, lastName, avatarUrl, id, email and username.

![image.png](https://images.zenhubusercontent.com/5f5f7b594bcdb266a00490dc/225d2596-958a-4051-aacd-3dbd9a2151ed)

**Comment by abdulmansour** [comment]
@razine-bensari added IT test aswell, leave me some feedback on it pls
