### ISSUE TITLE
Create 'Timeline' of followers transactions

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#28]
As a user I would like to see all the most recent transactions of my followers so I'm up to date

**To discuss**
- From the backend implement virtual scroll / load ?
- Load x at a time vs loading them all at once?

**Acceptance Criteria**
- See a list of transactions coming from your follower list sorted by date (newest ones appear at the top)
- This list will be composed of transaction components [1]

[1] A transaction component will have been created by then or it will have been made in another user story

**Comment by lindsaybangs** [comment]
Accepted 🚀
