### ISSUE TITLE
Updating User Does Not Encrypt Password

### ISSUE THREAD

**Issue by DPigeon** [DPigeon/Money-Tree#282]
**Describe the bug**
When a user tries to update its password, it does not get encrypted into the database.

**To Reproduce**
1. Send a POST request to the update endpoint
2. Look at the user's password in the database
3. Not encrypted

**Expected behavior**
The user's password should be encrypted even if it is being updated.

Bug reported by @EspressoCode

**Comment by EspressoCode** [comment]
This Bug will be addressed in the PR for  #182
