### ISSUE TITLE
When buying stocks, the previous transactions fulfilledStocks property become null 

### ISSUE THREAD

**Issue by EspressoCode** [DPigeon/Money-Tree#298]
**Describe the bug**
When user is buying stocks, the previous transactions' fulfilledStocks property become null. 

**To Reproduce**
1. Go to any stock page and buy any number of shares of that stock.
2. Check the response body to see that fulfilledstocks property of transaction has correct values.
3. Now go to any other stock page and make a new buy transaction by purchasing any number of shares of that stock.
4. If you check the values of fulfilledstocks you will see that the old transaction value became null.

**Expected behavior**
All the fulfilledStocks values for all transactions has to be preserved.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/33170291/108142743-35c01080-707b-11eb-960d-5bd195e7743d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by EspressoCode** [comment]
with a new implementation approach used in branch #273, we won't have this kind of bugs with relationships. Here is the document I created to explain the changes I made:
[Relationship.pdf](https://github.com/DPigeon/Money-Tree/files/6014557/Relationship.pdf)

@razine-bensari @wltrf @DPigeon  Let me know about your oponion and I can resolve this bug, I wanted to make sure this is good practice.

**Comment by wltrf** [comment]
I don't know much about the follow unfollow stuff, but I don't see anything wrong with your implementation. The others can probably provide more insight.

**Comment by DPigeon** [comment]
I just read the doc twice haha very well done. I am on board with that! I like the way we return only relevant info for the user when looking at the followers of the followers. Also using a followDao class is the perfect way to do it.

Amazing job!

**Comment by EspressoCode** [comment]
The bug is fixed in PR #315

**Comment by DPigeon** [comment]
> The bug is fixed in PR #315 

Nice. I was gonna look into that one soon too.

**Comment by EspressoCode** [comment]
Fixed by #315
