### ISSUE TITLE
Alpaca is not sending streams

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#300]
**Describe the bug**
Not able to connect to the websocket in the backend

**To Reproduce**
1. Run the backend
2. Go to http://jxy.me/websocket-debug-tool/
3. Enter the environment URL
4. It will not connect

**Expected behavior**
It should connect

**Additional context**

Bug reported by @Alessandro100

**Comment by DPigeon** [comment]
Will take some time to investigate and work on a patch for this tonight.

**Comment by DPigeon** [comment]
Update: Just investigated and it seems like this was a CORS issue on the local env. It will also be a bug on dev and prod environment. If we allow all connections, we get that we can connect to the WS server:
![1](https://user-images.githubusercontent.com/37888675/108288410-89edf200-715a-11eb-869e-1417171daba5.png)

And in the backend we see:
![2](https://user-images.githubusercontent.com/37888675/108288429-91150000-715a-11eb-864f-7ac47cac200a.png)

So for us to be able to test locally as well as having it to work properly and securely on all envs, we have to make a fix for a common allowed origin on the backend:
- if local/test --> allowed http://localhost:4200
- if dev/prod --> allowed https://localhost:4200, https://127.0.0.1

**Comment by DPigeon** [comment]
Update: integrated the alpaca session with the alpacaAPI streams. Ready to be tested on market hours tomorrow. If it is not working, I will dig deeper into the bug.

**Comment by DPigeon** [comment]
Update: was able to test during market hours. Passing in the oAuthToken into the alpaca session for streams just does not work. However, passing the keyId and secretId of a user works... So we may have to get those information as well.

**Comment by DPigeon** [comment]
Final update: Was able to regenerate a token properly and now the oAuthToken works with streams! Will be pushed with #277.
