### ISSUE TITLE
Tab title is client instead of "MoneyTree"

### ISSUE THREAD

**Issue by arthur-del** [DPigeon/Money-Tree#301]
When  going on https://money-tree.tech/, the default tab title is "client" and has the default Angular project icon 

**To Reproduce**on 
1. Go to https://money-tree.tech/ and look at tab title

**Expected behavior**
Expecting to see title: MoneyTree or something along those lines, with maybe the logo as icon

![image.png](https://images.zenhubusercontent.com/5e1e14c10fe859d66dd1d06d/016ee03f-cd0d-4845-a4bd-d9346ba5ec3a)

Bug reported by @arthur-del

**Comment by EspressoCode** [comment]
Thanks for creating this bug @arthur-del, I made a new PR that changes the title.
