### ISSUE TITLE
Buy/Sell Limit order not working

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#312]
**Describe the bug**
When a user submits a limit buy order, it executes as a market order

**To Reproduce**
1. Go to stock detail page
2. Limit buy 1 stock
3. See console / alpaca saying it was executed as a market order

**Expected behavior**
It should be executed as a limit order

**Screenshots**
This are the params going to the  server 
![image](https://user-images.githubusercontent.com/18631060/108754277-ba93aa00-7513-11eb-9d7b-7f1220dbf23b.png)

This is whats coming back
![image](https://user-images.githubusercontent.com/18631060/108754320-c7180280-7513-11eb-938d-de43e2252b4f.png)

NOTE:
- same applies with sell

Bug reported by @Alessandro100

**Comment by Alessandro100** [comment]
I just noticed that in the frontend we don't even pass the limit price. @DPigeon let me know the format of the limitprice variable for transaction

**Comment by DPigeon** [comment]
> I just noticed that in the frontend we don't even pass the limit price. @DPigeon let me know the format of the limitprice variable for transaction

I haven't work on the buy/sell endpoints. I'dhave to understand what is happening here before answering. Maybe @razine-bensari or @abdulmansour can help?

**Comment by razine-bensari** [comment]
for limit_* orders, the limit price needs to be provided in the payload, the boolean for market hours. Please refer to the order object for field names
