### ISSUE TITLE
Transaction status stuck on PENDING

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#313]
**Describe the bug**
The initial state of the transaction object is PENDING but when an order is fullfilled, the status should be changed to FILLED, but it doesn't and just stays on PENDING

**To Reproduce**
1. Buy a stock
2. Make sure it's fulfilled (can check on alpaca)
3. Check transaction object -> it's still pending 

**Expected behavior**
Once the transaction is fulfilled, the status of the transaction should be changed to FILLED

Bug reported by @Alessandro100

**Comment by DPigeon** [comment]
This was implemented in @razine-bensari PR #305.

**Comment by Alessandro100** [comment]
fixed in PR #305
