### ISSUE TITLE
Time series graph of stock

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#33]
As a user I want to be able to see and interact with a time-series chart of a specific stock

**Acceptance Criteria**
-Able to see historical data for different time ranges ex: (1d, 5d, 1m, 3m, 6m, 1y)
-Able to see current price
-Able to see the volume traded for a time period
-Able to interact ex: (zoom in, draw lines)

![btc_chart.PNG](https://images.zenhubusercontent.com/5f5f7b594bcdb266a00490dc/c71308c3-1a26-4e81-ad04-820ac3aae93d)

![image](https://user-images.githubusercontent.com/18631060/105851151-ac07b080-5fb0-11eb-9d36-af2d41ad3b36.png)

**Comment by lindsaybangs** [comment]
Accepted 💯
