### ISSUE TITLE
Leaderboard page

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#343]
As a user I would like to see the leaderboard page so I the app is more fun and competitive

Note
- The leaderboard is sorted by scores

**Acceptance Criteria**
- The design looks like the Figma design
- Show only the top 50 investors
- When clicking on the investors in the leaderboard, it should go to their profile page

![image.png](https://images.zenhubusercontent.com/5e160ea2cbe5be5b659938e7/7acb1299-6aa3-4fd0-8a84-3697798adbf3)

**Comment by EspressoCode** [comment]
Hi @wltrf , I just wanted to let you know that I finished styling of leaderboard page on this branch:
[https://github.com/DPigeon/Money-Tree/tree/feature/%23343-Leaderboard-page](url)

Please let me know if you have done work on the backend part of this story. I used fake data to add styling to the frontend. Ideally, the frontend needs a backend endpoint that can return a response with a sorted array of SanitizedUsers (sorted based on scores) including top investors' score, name and rank. Rank can be assigned in the frontend if it's easier, please update me with the latest status of the backend part, thank you.

**Comment by wltrf** [comment]
Scope of this story for backend, for reference only.

![Screenshot from 2021-03-22 13-39-29](https://user-images.githubusercontent.com/33789241/112033701-1867e180-8b14-11eb-8bd6-4c13bb9f7f3d.png)

**Comment by wltrf** [comment]
tests are almost done, fyi i use the following piece of code to generate users
```java
for(int i = 0; i < 75; i++){
            this.createUser(
                    User.builder()
                            .firstName("fname" + i)
                            .lastName("lname" + i)
                            .username("username" + i)
                            .email("email" + i + "@money-tree.tech")
                            .password("Hello123?/")
                    .build()
            );
  }`
and i set the score in the `createUser` method to `Math.random()*100`
