### ISSUE TITLE
Bad Request 400 When Getting Positions

### ISSUE THREAD

**Issue by DPigeon** [DPigeon/Money-Tree#370]
**Describe the bug**
When logging on https://dev.money-tree.tech/, we cannot get the Alpaca positions properly.

**To Reproduce**
1. Go to https://dev.money-tree.tech
2. Login and open developer tools on the right side
3. See 400 error for https://dev.money-tree.tech/api/alpaca/positions/27
4. `{"status":"BAD_REQUEST","timestamp":null,"message":"Arguments are null","debugMessage":null}`

**Expected behavior**
It should be a 200 error type on dev

**Screenshots**
![bug2](https://user-images.githubusercontent.com/37888675/113489149-7db2bf80-9490-11eb-9f7f-6bcfba7c45ef.png)

Bug reported by @DPigeon

**Comment by EspressoCode** [comment]
Apparently all the alpaca-related endpoints are failing on dev, there's a null pointer error related to websocket and I believe it can be where we are initializing the Alpaca Session.

**Comment by DPigeon** [comment]
Yeah I'll investigate that.

**Comment by DPigeon** [comment]
Fixed in https://github.com/DPigeon/Money-Tree/pull/381.
