### ISSUE TITLE
Display Important Fundamental Statistics

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#38]
As a user I want to be able to see fundamental stats concerning the stock (market cap, PB Ratio, PE Ratio, EPS, Dividend +more)

**Acceptance Criteria**

- Able to see market cap
- Able to see PB Ratio
- Able to see PE Ratio
- Able to see EPS
- Able to see Dividend
- more

![Image from iOS (10)](https://user-images.githubusercontent.com/18631060/96512810-0a452a80-122f-11eb-94f8-a23bc4393a84.png)

![Screen Shot 2020-11-02 at 2 21 52 PM](https://user-images.githubusercontent.com/18631060/97909799-c403c700-1d16-11eb-92cf-c64ef3a3dacd.png)

**Comment by lindsaybangs** [comment]
Reviewed and accepted on Monday, Feb 1st, 2021 at 2:30 PM
