### ISSUE TITLE
Display Stock Industry

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#39]
As a user I want to know the stock belongs to which industry ex: mining, tech, pharma...

**Acceptance Criteria**
- Able to see which industry the stock belongs to
- e2e test is written

![Screen Shot 2020-11-02 at 2 20 20 PM](https://user-images.githubusercontent.com/18631060/97909657-9880dc80-1d16-11eb-9e96-f0a6d0c460eb.png)

**Comment by lindsaybangs** [comment]
Accepted after demonstration on Friday, November 27
