### ISSUE TITLE
Display List of Top Investors

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#40]
As a user I want to be able to see the top investors on MoneyTree that are invested in the stock so that I can follow them and get better insights

**Acceptance Criteria**
- List of the top n users invested in the stock

![image](https://user-images.githubusercontent.com/18631060/105851119-a0b48500-5fb0-11eb-99dc-ff33a2bb84c5.png)

**Comment by lindsaybangs** [comment]
Accepted !
