### ISSUE TITLE
People who own this stock, also own these stocks

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#42]
As a user I want to see a recommended list that displays a list of stocks that are owned by people who also own this stock.

**Acceptance Criteria**
- A list of stocks that are owned by people who also own this stock; this could be done by ranking the highest distribution of commonly owned stocks first. 

ex: 60% of people who own AAPL also own TSLA, 30% of people of own AAPL also own GOOGL. So TSLA will be ranked 1st GOOGL 2nd.

![image](https://user-images.githubusercontent.com/18631060/105851029-837fb680-5fb0-11eb-996a-3e765c6ae868.png)

**Comment by lindsaybangs** [comment]
Accepted 🚀
