### ISSUE TITLE
Create domain diagram

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#47]
As a developer I would like to create a domain diagram so I can better explain my system

https://en.wikipedia.org/wiki/Domain_model

**Acceptance Criteria**
- The domain model will provide sufficient abstraction to give a high level overview of the system
- The domain model will be drawn with draw.io (unless there is a good reason to use something else)
- The domain model file will be added in the 'Software Architecture' folder in the google drive

**Comment by EspressoCode** [comment]
I read all the user stories and created a rough Relational Model that can be helpful for creating the domain model. Here is the link to a file I created on draw.io for all of us to be able to work on it at the same time, I put my work as notes in that file (no diagrams yet!), please see it here:

https://drive.google.com/file/d/1b3c6k5iXMYvzVF1qsQdKPIHKJykAQZMF/view?usp=sharing

I gave access to editing but let me know if you had access issues.

**Comment by DPigeon** [comment]
> I read all the user stories and created a rough Relational Model that can be helpful for creating the domain model. Here is the link to a file I created on draw.io for all of us to be able to work on it at the same time, I put my work as notes in that file (no diagrams yet!), please see it here:
> 
> https://drive.google.com/file/d/1b3c6k5iXMYvzVF1qsQdKPIHKJykAQZMF/view?usp=sharing
> 
> I gave access to editing but let me know if you had access issues.

I had also began to make a rough relational model draft but yours looks more completed. I'll add anything that's missing so that we can start the diagram soon !

**Comment by DPigeon** [comment]
Update: I have began the domain model in a new page in the diagram.
