### ISSUE TITLE
Search for a stock by name or symbol

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#51]
As a user I want to be able to search for a particular stock by entering the name or symbol of the stock

**Acceptance Criteria**
- Able to view a list of stocks that correspond with the entered query (either by name or symbol)
- Able to view the particular stock when searching for it by name or symbol
- Not result found if an invalid query is entered 

<img width="402" alt="Screen Shot 2020-10-15 at 5 26 06 PM" src="https://user-images.githubusercontent.com/18631060/96187770-9263c100-0f0b-11eb-929c-6054a61547af.png">
<img width="576" alt="Screen Shot 2020-10-15 at 5 28 29 PM" src="https://user-images.githubusercontent.com/18631060/96188078-174eda80-0f0c-11eb-956d-052766e01351.png">

**Comment by lindsaybangs** [comment]
Reviewed and accepted on Monday, Feb 1st, 2021 at 2:30 PM
