### ISSUE TITLE
Ability to place a market buy order

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#55]
As a user I would like to place a market buy order so I can acquire a stock at it's current value

**Acceptance Criteria**
- Ability to select market order
- Ability to input the quantity of shares they want to buy
- Ability to view the estimated final price
- Displace amount of money the user can spend
- *Have a tooltip saying 'Market orders might not fill at this exact price'
- Have form errors/guards if user tries buying more than they can afford (for market orders this means being under 5% of the total order). Example: user wants to buy 100$ of AAPL and has 100$ available to trade. He wouldn't be able to because market order might execute a little higher. He must have 105$ (5% within)

**Comment by lindsaybangs** [comment]
accepted 👍
