### ISSUE TITLE
Ability to place limit buy order

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#56]
As a user I would like to place a limit buy order so I can acquire a stock at an exact value

https://www.investopedia.com/terms/b/buy-limit-order.asp

**Acceptance Criteria**
- Ability to select limit order
- Ability to input the quantity of shares they want to buy
- Ability to view the exact final price
- Displace amount of money the user can spend
- *Have a tooltip saying 'Limit orders fill at exact price'
- Have form errors/guards if user tries buying more than they can afford

**Comment by lindsaybangs** [comment]
Accepted 🚀
