### ISSUE TITLE
Ability to place limit sell order

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#57]
As a user I would like to place a limit sell order so I can sell a stock at an exact value

https://www.investopedia.com/terms/l/limitorder.asp

**Acceptance Criteria**
- Ability to select limit sell order
- Ability to input the quantity of shares they want to sell
- Ability to view the exact final price they will get when they sell
- Display amount of shares the user can sell
- Display total value of shares
- *Have a tooltip saying 'Limit orders fill at exact price'
- Assure there are form errors/guards if user tries selling more shares than they own

**Comment by lindsaybangs** [comment]
Accepted 🚀
