### ISSUE TITLE
Ability to place market sell order

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#58]
As a user I would like to place a market sell order so I can sell a stock at the current price

https://www.investopedia.com/terms/l/limitorder.asp

**Acceptance Criteria**
- Ability to select market sell order
- Ability to input the quantity of shares they want to sell
- Ability to view the estimated final price they will get when they sell
- Display amount of shares the user can sell
- Display total value of owned shares at market value
- *Have a tooltip saying 'Market orders might not fill at this exact price'
- Assure there are form errors/guards if user tries selling more shares than they own

**Comment by Alessandro100** [comment]
Its written, must be tested when the stock market is open

**Comment by lindsaybangs** [comment]
Accepted 💯
