### ISSUE TITLE
Determine best method to AnalyzingCode Quality and create Security Report

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#6]
As a developer I want to research the best method to create code analysis and security reports so future code stays clean and accountable for

**Acceptance Criteria**
- A proposed solution detailing why the chosen technology was selected
- The above answer added into the research document in the google drive

**Comment by DPigeon** [comment]
@wltrf We have chosen SonarCloud in the end because we made our repo public. Next step would be to write an explanation about it in the research document.
