### ISSUE TITLE
View the status of orders

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#60]
As a user I would like to see the status of my past and present orders so I can refer to them

Possible Statuses: Completed, Pending, Cancelled, Partially Filled*
**to be determined

**Acceptance Criteria**
- See the date of the order
- See the status of the order
- Sort orders by most recent
- See the quantity purchased / sold
- See the average fill price per share
- See the type of order (market buy, market sell, limit buy, limit sell)
- See the name and symbol of the company

![image](https://user-images.githubusercontent.com/18631060/105851310-e709e400-5fb0-11eb-94a0-c7887c42e392.png)

**Comment by lindsaybangs** [comment]
Accepted 🚀
