### ISSUE TITLE
Notify user immediately when status changes

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#61]
As a user I would like to be notified immediately when the status of my order changes

**Note**
We'll need a pub/sub or websocket type architecture as this change will only be notified in the backend. The backend will need to notify the frontend of the change (which is not very standard for REST APIs)

**Acceptance Criteria**
- Send an email to the user when one of their orders is completed
- [If user is on the client] Update data on the page with the most recent order

**Comment by lindsaybangs** [comment]
accepted 🚀
