### ISSUE TITLE
Create Component Diagram

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#62]
As a developer I would like to have a component diagram to better express my product to other developers

Note
Component diagrams are used in modelling the **physical** aspects of object-oriented systems

**Acceptance Criteria**
- Assure that the component diagram provides sufficient detail in modelling the physical aspects of the system
- Assure that the component diagram is written with draw.io
- Assure that the component diagram when done is put in the 'Software Architecture' folder in google drive

**Comment by razine-bensari** [comment]
Please Review component diagram. (https://drive.google.com/drive/folders/1b6gkBcbcV1NFRM4A4me-Da5x4fvO8Js9)

No PR needed since the component diagram was made using draw.io

**Comment by wltrf** [comment]
Looks good to me

**Comment by DPigeon** [comment]
Looks good! We may have to change the database protocol to HTTP instead of BOLT depending on the outcome of this story https://github.com/DPigeon/Money-Tree/issues/103.
