### ISSUE TITLE
Create ER Model

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#64]
As a developer I would like to have a ER Model to better understand how data works in our system

**Acceptance Criteria**
- A sufficient amount of detail is added in the ER Model to be able to implement it into a schema
- The ER Diagram is done in Draw.io
- It's added to the 'Software Architecture' folder in google drive

https://drive.google.com/drive/folders/1mdX7FY28Lc0NDucHu71Lq292xPaPojFA?usp=sharing

**Comment by abdulmansour** [comment]
![MoneyTree ER Diagram.png](https://images.zenhubusercontent.com/5f5f7b594bcdb266a00490dc/12a49b3e-2d4e-4ec1-af4c-1b72dc199f0c)
