### ISSUE TITLE
Analysis of external libraries

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#65]
As a developer I would like to analyze the external libraries of the product so I know what risks to take

**Acceptance Criteria**
- Analyze Alpaca (is it secure? functionality?)
- Analyze Angular Material (is it comprehensive enough?)
- Analyze Jest / Protractor (e2e) and Spock (do they have reports?)

https://docs.google.com/document/d/1pEgTp4gpPSbUNVYRu4M4uHlWOzklrnOMEdVTabhqBug/edit

**Comment by Alessandro100** [comment]
@razine-bensari  @DPigeon can you guys review this? All the information can be found in this doc https://docs.google.com/document/d/1pEgTp4gpPSbUNVYRu4M4uHlWOzklrnOMEdVTabhqBug/edit?usp=sharing

**Comment by razine-bensari** [comment]
On it

**Comment by DPigeon** [comment]
> @razine-bensari @DPigeon can you guys review this? All the information can be found in this doc https://docs.google.com/document/d/1pEgTp4gpPSbUNVYRu4M4uHlWOzklrnOMEdVTabhqBug/edit?usp=sharing

Just reviewed. 
About the EGS scores: have we found good websites to scrape that data from? I'm just curious.
Overall it looks good!

**Comment by razine-bensari** [comment]
Yeah, my only question is about IEXCloud. Overall I would put the ticket to close and discuss IEXCloud from a functional perspective in slack.

Good Job! Excited to start putting all the pieces together!
