### ISSUE TITLE
Create UI Mockups

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#66]
As a developer I would like to see the UI mockups so I can more easily build the application

**Note**
When adding UI component, use components from https://material.angular.io/ this will speed up mock up build time + be more consistent

**Good Resources For Design Inspiration**
https://dribbble.com/
https://icdn2.digitaltrends.com/image/digitaltrends/light-mode_home_1500x1500_eng-jv-png-img-fullhd-medium-copy.jpg
https://cdn.dribbble.com/users/1753227/screenshots/14045734/media/0d778300272a44f0cf070133cbd2779e.png
https://design4users.com/ui-design-finance-apps/
https://www.wealthsimple.com/en-ca/product/trade

**Acceptance Criteria**
- Design the mockups with figma (Desktop)
- Assure the design takes into account the user personas (must have visible accommodations for them)
- Assure the design includes all of our user stories (link the mockup designs with the user story)
- Assure the figma document is in the 'Design' folder in google drive

**Comment by EspressoCode** [comment]
This is the link to our work on UI Mockups and Prototypes:
https://www.figma.com/file/wd5NH7WWduvtduB5IHw7rQ/MoneyTree?node-id=222%3A1970
