### ISSUE TITLE
Setup Linter

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#71]
As a developer I would like to have a linter in my project so that the code stays consistently formatted

**Note**
Use husky for pre-commit

**Acceptance Criteria**
- A linter is setup in the frontend 
- A linter is setup in the backend
- The rules of the linter will abide by our coding guidelines*
- The linters will prevent code from being commit if the code doesn't follow it

**Comment by DPigeon** [comment]
The husky depency has been added on the frontend. A pre-commit will run the lint & unit tests before commiting on the frontend.
![setup-linter-frontend](https://user-images.githubusercontent.com/37888675/94953234-303fa080-04b5-11eb-83ff-d66d16f2fadc.png)

**Comment by DPigeon** [comment]
Unfortunately, we cannot use husky with the frontend and backend at the same time. Husky will work with the frontend. However, to be able to have a pre-commit linter on the backend as well, the pre-commit hooks have to be overwritten. 

I'm currently looking for a solution for this. We could achieve this by creating some pre-commit shell script but everyone would have to replace their pre-commit hooks script with the one created.

**Comment by DPigeon** [comment]
Update: To bypass the husky limitation, I have written a small script. Everything will be documented in a PR.
