### ISSUE TITLE
View ranked leaderboard

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#78]
As a user I want to be able to view the top investors of the platform based on a ranking criteria

**Acceptance Criteria**
- User is able to see the leaderboard which contains the top platform investors ranked according to the ranking criteria

***Ranking Criteria**: TBD(could be net profit, roe, transaction count, formula that mixes all three, etc...)

**Comment by DPigeon** [comment]
@Alessandro100 this can be closed right?
