### ISSUE TITLE
Propose DevOps pipeline

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#8]
As a developer I would like to know the best solution to implement devops into our workflow so that good quality code passes and bad code get filtered automatically

**Notes**
The acceptance criteria is based on my understanding of devops, if there is something conflicting / something that doesn't make sense, let me know and we can come to a solution - Alessandro

**Acceptance Criteria**
- A technology is chosen and is backed up (jenkins, travis, github actions, etc)
- A flow is proposed and an explanation why is written. (flow example: lint -> test -> build -> etc)
- The proposal takes into account different environments (example: when pushing code on dev environment -> deploy on UAT, when PR gets accepted into master -> push onto prod environment)
- The above solution is added into the research document in google drive

**Comment by DPigeon** [comment]
I have thought about the build and deploy phase. 

Since we're now using a public repo, we have unlimited GitHub Actions minutes and packaging space. Therefore we can store all our artifacts on GitHub Actions (just like DockerHub). Then, we can easily use that artifact and deploy it remotely to our hosting service. Docker can be installed to that hosting service and we can simply run the image we just pulled from the GitHub Actions artifactory remotely on the pipeline.

**Comment by Alessandro100** [comment]
Amazing research and proposal guys, looks like a very comprehensive DevOps pipeline! I have a questions:
So from my understanding
feature branch -> PR -> (Lint, Tests, Packaging and SonarCloud) -> [accepted] dev branch -> (Build, Publish and Deploy) -> uat branch -> [approved UAT PR] -> master branch ->  (Build, Publish and Deploy) prod environment

I'm confused on the "After the pull request is approved on the uat branch" section. Does this mean the user will have to create 2 PRs? How would this work?

**Comment by DPigeon** [comment]
> Amazing research and proposal guys, looks like a very comprehensive DevOps pipeline! I have a questions:
> So from my understanding
> feature branch -> PR -> (Lint, Tests, Packaging and SonarCloud) -> [accepted] dev branch -> (Build, Publish and Deploy) -> uat branch -> [approved UAT PR] -> master branch -> (Build, Publish and Deploy) prod environment
> 
> I'm confused on the "After the pull request is approved on the uat branch" section. Does this mean the user will have to create 2 PRs? How would this work?

Yes. So the developer will have to create 2 PRs to be able to deploy to the right environment. Basically, as soon as a feature is ready and that the CI pipeline gets approved, it gets merged onto the dev branch. From there, the dev branch can be deployed on the uat branch whenever the developer wants. So yes another PR will have to be created there when we know we that are ready to send our new feature build to the uat branch. When the CD pipeline passes, then a new version is available on our free tier environment and the build is now on the uat branch. On that branch, we can push some last "pre-prod fixes/hotfixes" if needed. Then, when everything has been tested on the pre-prod environment free tier, we deploy with another PR to master branch to have our real app running in prod.

**Comment by Alessandro100** [comment]
ahh I see, I think there is a way we can do it without having 2 PRs. I'd like to get the input from @lindsaybangs. Worst case, we'll stick with the 2 PR system

**Comment by DPigeon** [comment]
Maybe having two different jobs on the CD pipeline (Build --> Publish --> Deploy-uat [manual] --> Deploy-prod [manual] ) when making a PR to uat or master would be a better solution. So by doing that, we could simply choose which deployment we want to trigger manually with a simple click. It could be possible with GitHub Actions. See it [here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow).

**Comment by DPigeon** [comment]
I have reviewed the devops pipeline on the research document and everything seems good!
I have made a diagram for the pipeline. We can refer to it at any time. The draw.io diagram is in the Google Drive of the project.

![DevOpsPipeline](https://user-images.githubusercontent.com/37888675/94091939-817dcf00-fde7-11ea-9ca6-60c13c977815.png)
