### ISSUE TITLE
Adjust User Score After Market Transaction

### ISSUE THREAD

**Issue by abdulmansour** [DPigeon/Money-Tree#80]
As a user I want to be assigned a leaderboard score after every market transaction

*Transaction score value: based on the ranking criteria(tbd), each transaction will have a calculated value associated with it that will be added to the user's leaderboard score

**Acceptance Criteria**
- A transaction score value is added to the user's leaderboard score after a successfully completed transaction

**Comment by lindsaybangs** [comment]
Accepted 💯
