### ISSUE TITLE
Summary of User Stories

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#88]
As a developer I would like to add the summary of the user stories in our delivery document

**Notes:**
Discuss that we use Zenhub to handle this stuff
Summary of all user stories (Total number of issues, total user story points, the epics)

**Acceptance Criteria**
- the according text is in the delivery document

**Comment by Alessandro100** [comment]
This information can be found in the delivery document section 2 Requirements

**Comment by razine-bensari** [comment]
Nice work, wanted to suggest improvment but they are already implemented!!! Really good job Alessandro
