### ISSUE TITLE
Determine best hosting service

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#9]
As a developer I want to know the best place to host my application so other users will be able to access it outside of my computer

**Questions**
[Backend] For our development environment (UAT) wouldn't it be ok to use a service with a free tier? For our production environment we will need a paid service as it will be client facing - Alessandro

**Acceptance Criteria**
- Propose the best hosting for an Angular application. Explain why it was chosen and how it fits our needs for UAT and production
- Propose the best hosting solution for a GO application. Explain why it was chosen and how it fits our needs for UAT and production
- Determine if we will have funding from Concordia
- Answer all the above in the 'research' document in the google drive

**Comment by DPigeon** [comment]
Just curious: would we need two different hosting service --> one for uat (free one) and another one for production (paid one) ? 

Could we simply use the same hosting service to deploy both environments ?

**Comment by Alessandro100** [comment]
Ideally we would use the same hosting service allowing for 1 with a free tier and one with a paid tier. Based on the google research document I saw that you added and researched many choices. Which one do you suggest we pick based on your research?

**Comment by DPigeon** [comment]
I'll let @abdulmansour or @razine-bensari answer that one as I didn't do the final research for that.
