### ISSUE TITLE
Summary of Software Architecture 

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#90]
As a developer I would like to see the summery of the software architecture documents

Note
Include: Domain Model, ER Diagram, Class Diagram, Justification of design patterns, analysis of external libraries
Bonus: Include devops architecture

**Acceptance Criteria**
- All the included diagrams and descriptions are found in the deliverable document

**Comment by wltrf** [comment]
I'll take care of this

**Comment by DPigeon** [comment]
I'll work a bit on this story. I can also write a summary of the DevOps pipeline as a last section if needed.

**Comment by DPigeon** [comment]
@abdulmansour @razine-bensari @wltrf I'll let you guy's take the other part.

**Comment by razine-bensari** [comment]
Thks, im working on it in a few hours, gotta finish setting up my tempo!
