### ISSUE TITLE
Summary of code review

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#95]
As a developer I would like to see how we review code so I can write better code

**Notes**
Show our PR template + how we need at least one reviewer to accept
Show samples of past PRs

**Acceptance Criteria**
- have all the text in the delivery document

**Comment by DPigeon** [comment]
Since we're approach the end of the sprint, I'll put this as in progress now since I already started on it.

**Comment by DPigeon** [comment]
All PRs with code reviews are #72 #85 #86 #106 #112 #123 #124 #125 #127 and more to come. They will be documented on the report.
