### ISSUE TITLE
Setup backend architecture

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#99]
As a developer I would like to setup the backend architecture so that it sets the base fo future work to go faster

Definition of setup:
Create all the class files, link them but the functionality of these functions found in the class diagram don't have to be implemented

**Acceptance Criteria**
- [x] Models are created 
- [x] Controllers are created
- [x] Services are created
- [x] The architecture diagrams are respected: ER diagram, Class diagram, component diagram
- [x] Integration Tests

**Comment by razine-bensari** [comment]
A few thing that can be divided:

1) Add classes from achitecture diagrams and skeleton methods that we think we will need

2) Make sure the nodes and relationship are properly configured and persisting works well

3)Write the tests

4) Connect Facade with the external apis

5) Write integration tests for controllers

**Comment by DPigeon** [comment]
We just had a meeting and talked about dividing the work. This story is the **base** architecture for the backend. Everyone working on the backend will be involved in this. It also has some deeper *sub-tasks*for the implementation and connection through the APIs and backend.

- Neo4j Sub-task: #110  (assigned to Razine)
- IEXCloud Sub-task: #109 (Assigned to Abdul)
- Alpaca Sub-task: #108 (Assigned to myself & Walter)
